
package Views;

import model.Livro;
import Dao.LivrosDao;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/** Classe SobreLivros()
 *
 * @author pedro
 * Nessa tela contém os dados do livro escolhido pelo usuário em uma das telas de Listar Livro. 
 * @version 1.0
 * @since 30/05/2024
 */
public class SobreLivros extends javax.swing.JFrame {  
    public int TelaAdmin;
    public String id;

 /** PuxarBanco()
 * Este método serve para pegar as informações do livro que o usuário deseja alterar e configurálos nos campos da tela. Observe que é utilizado a varíavel pública Id para o sistema saber qual livro pegar os dados do banco de dados.
 */
    
    
    public void PuxaBanco() {

        LivrosDao livrosdao = new LivrosDao();

        for (Livro livro : livrosdao.ListarApenasUm(id)) {
            
            
            String Nome = livro.getNome();
            String Autor = livro.getAutor();
            String Editora = livro.getEditora();
            String Categoria = livro.getCategoria();
            String Sinopse = livro.getSinopse();
            String DataPublicacao = formatarData(livro.getDataPublicacao());

            jNomeLivro.setText("<html>" + Nome + "</html>");
            jAutorLivro.setText("<html>" + Autor + "</html>");
            jEditoraLivro.setText(Editora);
            jCategoriaLivro.setText(Categoria);
            jAnoLivro.setText(DataPublicacao);
            jSinopseLivro.setText("<html>" + Sinopse + "</html>");

        }
        
    }

    /** mostrarDetalhes(int idLivro)
     * Método usado para armazenar as informações do Livro que vieram do banco de dados na tela.
 *  @param idLivro serve para armanezar o Id do Livro selecionado pelo usuário e pegar as informações desse livro especifico.
 */   

    public void mostrarDetalhes(int idLivro) {
        LivrosDao livroDao = new LivrosDao();
        Livro livro = livroDao.buscarLivroPorId(idLivro);

        // Atualize os componentes da interface com as informações do livro
        jNomeLivro.setText(livro.getNome());
        jAutorLivro.setText("Autor: " + livro.getAutor());
        jEditoraLivro.setText("Editora: " + livro.getEditora());
        jCategoriaLivro.setText("Categoria: " + livro.getCategoria());
        jAnoLivro.setText("Data de Publicação: " + livro.getDataPublicacao());
        jSinopseLivro.setText(livro.getSinopse());
    }

    
    /** formatarData(String data)
     *  Este método serve para formatar a data e deixá-la no formato certo.
     * @param data neste parâmetro entra a data no formato inglês AAAA-mm-dd
     * @return este método retorna a data no formato brasileiro dd/mm/AAAA
     */
    private String formatarData(String data) {
        try {
            SimpleDateFormat formatoOriginal = new SimpleDateFormat("yyyy-MM-dd");
            Date dataOriginal = formatoOriginal.parse(data);
            SimpleDateFormat formatoBrasileiro = new SimpleDateFormat("dd/MM/yyyy");
            return formatoBrasileiro.format(dataOriginal);
        } catch (Exception e) {
            e.printStackTrace();
            return data;
        }

    }

    /**
     * Cria a tela SobreLivros() aonde será inicializado os dados dessa tela.
     */
    public SobreLivros() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jNomeLivro = new javax.swing.JLabel();
        jAutorLivro = new javax.swing.JLabel();
        jAnoLivro = new javax.swing.JLabel();
        jCategoriaLivro = new javax.swing.JLabel();
        jEditoraLivro = new javax.swing.JLabel();
        jSair = new javax.swing.JButton();
        jSinopseLivro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Nome do livro:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 200, 172, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Categoria:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(770, 200, 149, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Sinopse:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 340, 96, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Ano de publicação:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(540, 660, 220, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Editora:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(770, 360, 90, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Autor:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(770, 540, 140, 32);

        jNomeLivro.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        getContentPane().add(jNomeLivro);
        jNomeLivro.setBounds(370, 240, 280, 70);
        jNomeLivro.getAccessibleContext().setAccessibleDescription("");

        jAutorLivro.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        getContentPane().add(jAutorLivro);
        jAutorLivro.setBounds(770, 580, 330, 70);

        jAnoLivro.setFont(new java.awt.Font("Segoe UI", 2, 28)); // NOI18N
        getContentPane().add(jAnoLivro);
        jAnoLivro.setBounds(540, 710, 230, 40);

        jCategoriaLivro.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        getContentPane().add(jCategoriaLivro);
        jCategoriaLivro.setBounds(770, 240, 280, 90);

        jEditoraLivro.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        getContentPane().add(jEditoraLivro);
        jEditoraLivro.setBounds(770, 410, 310, 100);

        jSair.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jSair.setText("Voltar");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        getContentPane().add(jSair);
        jSair.setBounds(70, 850, 140, 40);

        jSinopseLivro.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jSinopseLivro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jSinopseLivro);
        jSinopseLivro.setBounds(310, 400, 360, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/** Botão SAIR
 * Caso o usuário seja administrador, ele voltará para a tela de listar livros como administrador. Caso contrário, voltará para a tela de listar livros do usuário normal.
 * 
 * @param evt 
 */
    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        // TODO add your handling code here:
        ListarLivrosAdmin lll = new ListarLivrosAdmin();
        
         
        if(this.TelaAdmin == 0){
        ListarLivros livro = new ListarLivros();
        livro.setVisible(true);
        this.dispose();
        } else {
            lll.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jSairActionPerformed

    /** Aqui são inicializadas a tela SobreLivros.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SobreLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SobreLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SobreLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SobreLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        SobreLivros sobreLivros = new SobreLivros();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sobreLivros.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAnoLivro;
    private javax.swing.JLabel jAutorLivro;
    private javax.swing.JLabel jCategoriaLivro;
    private javax.swing.JLabel jEditoraLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jNomeLivro;
    private javax.swing.JButton jSair;
    private javax.swing.JLabel jSinopseLivro;
    // End of variables declaration//GEN-END:variables
}
